blank_issues_enabled: true
contact_links:
  - name: ğŸ  NL Design System
    url: https://nldesignsystem.nl
    about: De homepage van NL Design System
  - name: âœ¨ Candidate componenten
    url: https://nldesignsystem.nl/componenten/?filter=community&filter=helpWanted&filter=todo
    about: Componenten met de 'Candidate' status
