blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Slack
    url: https://nldesignsystem.nl/slack/
    about: Stel je vragen in Slack, waar de community en het kernteam dagelijks antwoord geven.
  - name: ğŸ§‘â€ğŸ’» Online bijeenkomsten
    url: https://nldesignsystem.nl/community/events/overzicht/
    about: Kom naar de wekelijkse developer open hour of tweewekelijkse design open hour om vragen te bespreken
  - name: ğŸ“ NL Design System kernteam
    url: https://nldesignsystem.nl/project/kernteam/
    about: Contact opnemen met het kernteam
