name: Chromatic for pull requests

on:
  workflow_run:
    workflows:
      # On PR, to trigger visual regression testing
      - Continuous Integration
      # On push to main, to set new baseline
      - publish
    types:
      - completed

permissions:
  # Read the contents of the repo
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  chromatic:
    # Only run if the Continuous Integration workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Use the correct ref to check out
          ref: ${{ github.event.workflow_run.head_sha }}
          # Make sure that history is available to Chromatic
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version and cache
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing dependencies. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download visual-regression-testing artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: visual-regression-testing
          # Needed to download an artifact created in a different workflow
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          path: packages/storybook-test/dist/

      - name: Chromatic
        uses: chromaui/action@4c20b95e9d3209ecfdf9cd6aace6bbde71ba1694 # v13.3.4
        with:
          autoAcceptChanges: main
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBaseDir: packages/storybook-test/
          storybookBuildDir: packages/storybook-test/dist/
          storybookConfigDir: packages/storybook-test/config/
          exitOnceUploaded: true
          onlyChanged: true
