name: Codecov for pull requests

on:
  workflow_run:
    workflows:
      # Triggered by the Continuous Integration workflow
      - Continuous Integration
    types:
      # Only when the Continuous Integration workflow completes
      - completed

permissions:
  # Read the contents of the repo
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    # Only run if the Continuous Integration workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Check out the same ref that Continuous Integration ran for
          ref: ${{ github.event.workflow_run.head_sha }}
          # Make sure that history is available to Codecov
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node.js version and cache
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download coverage-report artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: coverage-report
          # Needed to download an artifact created in a different workflow
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload coverage to codecov.io
        id: codecov-action
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          fail_ci_if_error: true
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ secrets.CODECOV_TOKEN }}
